# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "vector<bool>{ true, true, false };"
email: vectorofbool@gmail.com
description: The creations of a mad(dening) template specialization
baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://vector-of-bool.github.io" # the base hostname & protocol for your site
url: "http://localhost:4000"
twitter_username: jekyllrb
github_username:  vector-of-bool

# Build settings
markdown: kramdown
theme: minima

image:
  source: assets/images/_fullsize
  presets: {}

digits: [1,2,3,4,5,6,7,8,9]

gems:
  - jekyll-minifier

jekyll-minifier:
  exclude: '*.js'